# Generated by Django 4.2.2 on 2023-07-02 18:56

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Brand',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('NameBrand', models.CharField(max_length=25, verbose_name='Бренд')),
            ],
        ),
        migrations.CreateModel(
            name='Category',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('NameCategory', models.CharField(max_length=50, verbose_name='Категория')),
            ],
        ),
        migrations.CreateModel(
            name='Product',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Photo', models.ImageField(upload_to='images/')),
                ('Name', models.CharField(max_length=50, verbose_name='Название')),
                ('Price', models.CharField(max_length=50, verbose_name='Цена')),
                ('Description', models.TextField(max_length=500, verbose_name='Описание')),
            ],
        ),
        migrations.CreateModel(
            name='UnderCategory',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('NameUnderCategory', models.CharField(max_length=50, verbose_name='Под категория')),
            ],
        ),
    ]
