# Generated by Django 4.2.2 on 2023-07-02 19:03

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('fish', '0002_alter_brand_options_alter_category_options_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='product',
            options={'ordering': ['Name'], 'verbose_name_plural': 'Продукт'},
        ),
        migrations.AddField(
            model_name='product',
            name='BrandProduct',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='fish.brand', verbose_name='Бренд'),
        ),
        migrations.AlterField(
            model_name='product',
            name='Name',
            field=models.CharField(max_length=50, verbose_name='Название продукта'),
        ),
    ]
