# Generated by Django 4.2.2 on 2023-07-02 19:07

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('fish', '0003_alter_product_options_product_brandproduct_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='CategoryProduct',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='fish.category', verbose_name='Категория'),
        ),
        migrations.AddField(
            model_name='product',
            name='UnderCategoryProduct',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='fish.undercategory', verbose_name='Под категория'),
        ),
        migrations.AlterField(
            model_name='product',
            name='Photo',
            field=models.ImageField(upload_to='images/', verbose_name='Фото'),
        ),
    ]
